cmd/jwtclient/auth_mux.go

fix:may use a nil jwt-client interface

fix:may use a nil jwt-client interface

---

auth/app.go
auth/jwt.go
auth/mapper.go
auth/transport.go
cli/api.go
cli/user.go
cmd/jwtclient/auth_mux.go
script/mysql.sql
storage/badger.go
storage/mysql.go
storage/store.go

user request limit by amount/duration

user request limit by amount/duration

---

cmd/jwtclient/auth_mux.go

if 'pattern' with '/' as suffix, 'TrustHandler' treat it as a root path,
that it's all sub-path will be trusted.
if 'pattern' without '/' suffix,
only the URI exactly matches the 'pattern' would be treat as trusted.

change the logical of 'TrustHandle' to following describtion:

---

core/const.go
go.mod
go.sum

update gin package
update version

prep for v1.3.1

---

auth/app.go
auth/jwt.go
auth/route.go
auth/transport.go
cli/api.go
cli/api_test.go
cmd/jwtclient/client.go
storage/mysql.go

1 fix HasMiner api
2 rename func name: GetMiner to GetUserByMiner

fix: api: HasMiner returns not correct 

---

storage/mysql.go
storage/store_test.go

fix GetUserByMiner on mysql.
add unit test for GetUserByMiner

fix: GetUserByMiner on mysql

---

cmd/jwtclient/auth_client.go
cmd/jwtclient/auth_client_test.go
cmd/jwtclient/auth_mux.go
go.mod

refactor 'NewAuthMux' method, remove `log` param.

refactor: refactor 'NewAuthMux' method

---

.gitignore
auth/app.go
auth/jwt.go
auth/mapper.go
auth/route.go
auth/transport.go
cli/token.go
cli/user.go
cmd/jwtclient/auth_client.go
core/const.go
go.mod
storage/badger.go
storage/badger_helper.go
storage/mysql.go
storage/store.go
storage/store_test.go

1. add cmds: delete user and get token
2. using soft deleteion (`user` and `token`)

add cmds and soft deleteion

---

cli/miner.go
cli/user.go

resolved filecoin-project/venus#4878

opt: Cmd fmt and paras for add user

---

Makefile
dockerfile

change to build docker image from local repo rather than from git chech out

fix: venus-auth ：change to build image from local repo

---

cli/run.go

fix https://github.com/filecoin-project/venus/issues/4995
add sub command to attach mysql db when service start

feat #4995 : venus-auth : add sub command to attach mysql db when service start 

---

docker/script/compose.sh

fix https://github.com/filecoin-project/venus/issues/4996
update user add command used in docker

fix #4996 : venus-auth docker :  update user add command used in docker compose script

---

docs/en/getting-started.md
docs/zh/快速上手.md

从venusdocs文档迁移。
fix https://github.com/filecoin-project/venus/issues/5012

docs: migrate docs from venus-docs

---

cmd/server/main.go

resolve: https://github.com/filecoin-project/venus/issues/4964

fix: rename OAUTH_HOME to VENUS_AUTH_PATH

---

.github/workflows/build_upload.yml
.github/workflows/go.yml

chore:
1. add build check
2. add git-based repo change check.
3. only run auto-release after PR merged
would fixes https://github.com/filecoin-project/venus/issues/5096

chore: chores related to git-actions

---

auth/jwt_test.go
go.mod
go.sum
integrate_test/miner_test.go
integrate_test/mock_deamon.go
integrate_test/ratelimit_test.go
integrate_test/token_test.go
integrate_test/user_test.go
storage/mysql_test.go
util/util_test.go

Add more unit tests for the venus-auth package.

tests: add more unit tests

---

docker/script/compose.sh

close https://github.com/filecoin-project/venus/issues/5173
no init when discover token file in repo

fix: 避免在docker-compose重启时，auth重复创建初始token / no reinit when compose reload

---

.github/workflows/build_upload.yml
.github/workflows/docker_image.yml
.github/workflows/go.yml

resolve https://github.com/filecoin-project/venus/issues/5002

ci: 拆分git工作流/split git workflow

---

jwtclient/inteface.go

involve  https://github.com/filecoin-project/venus/issues/5193
- add RandSecret func

feat: add func to make rand secreat

---

core/const.go

chore: bump version to v1.7.0

---

core/const.go

chore: backport 100

---

Makefile

involve  https://github.com/filecoin-project/venus/issues/5267
- rm BUILD_DEPS in makefile

fix: rm BUILD_DEPS in makefile

---

auth/app.go
auth/jwt_test.go
auth/transport.go
integrate_test/miner_test.go
integrate_test/ratelimit_test.go
integrate_test/token_test.go
integrate_test/user_test.go
jwtclient/auth_client_test.go
storage/mysql.go
storage/mysql_test.go
storage/store.go
storage/store_test.go

close filecoin-project/venus/issues/5306
增加STM annotaiton

feat: add STM annotations/增加STM注解

---

core/const.go
go.mod

https://github.com/filecoin-project/venus/issues/5350

chore: bump version to v1.8.0-rc1

---

auth/jwt.go
auth/jwt_test.go
auth/transport.go
cli/miner.go
integrate_test/miner_test.go
jwtclient/auth_client.go
jwtclient/auth_client_test.go
storage/badger.go
storage/badger_helper.go
storage/mysql.go
storage/mysql_test.go
storage/store.go
storage/store_migration.go
storage/store_test.go

feat: add open-mining field for miner

---

jwtclient/auth_client.go

fix: add OpenMining for ListUsersWithMiners

---

auth/jwt.go
storage/badger.go
storage/badger_helper.go
storage/mysql.go
storage/mysql_test.go
storage/store.go

fix: The assignment of the Gorm structure zero for mysql

---

auth/jwt.go
jwtclient/auth_client.go
storage/badger.go
storage/badger_helper.go
storage/mysql.go
storage/mysql_test.go
storage/store.go

Chore/merge master to 1.9

---

storage/mysql.go
storage/mysql_test.go

fix: fix GetUserBySigner

---

core/const.go
go.mod
go.sum

https://github.com/filecoin-project/venus/issues/5401

chore: bump version to v1.8.0

---

.circleci/config.yml

sub task of： https://github.com/filecoin-project/venus/issues/5220
circleci tests for STM enhancement

feat: circleci tests for STM enhancement

---

storage/mysql.go

close filecoin-project/venus#5504

fix: migrate mysql to v3

---

core/const.go

chore: bump version to v1.9.0-rc1

---

jwtclient/auth_client.go

close https://github.com/filecoin-project/venus/issues/5541

feat: replenish auth client interface

---

auth/jwt_test.go
auth/transport.go
cli/user_miner.go
jwtclient/auth_client.go
storage/badger.go
storage/mysql.go
storage/mysql_test.go
storage/store.go
storage/store_test.go

close filecoin-project/venus#5524

fix: Correctly handle the zero value in the api / 正确处理接口中参数的零值

---

jwtclient/auth_client.go

feat: replenish auth client interface / 补充 auth client 

---

auth/route.go

feat: add middle ware to rewrite address in url params / 重写url中的地址参数

---

auth/jwt.go
auth/jwt_test.go
auth/route.go
auth/transport.go
cli/miner.go
cli/signer.go
cli/token.go
cli/user.go
cli/user_miner.go
cli/user_signer.go
integrate_test/miner_test.go
integrate_test/ratelimit_test.go
integrate_test/signer_test.go
integrate_test/token_test.go
integrate_test/user_test.go
jwtclient/auth_client.go
jwtclient/auth_client_test.go
jwtclient/limiter_warper.go

close https://github.com/filecoin-project/venus/issues/5547

feat: simplify interface of authClient and add ctx / 简化 authClient 接口并增加 context

---

auth/jwt.go
auth/jwt_test.go
storage/badger.go
storage/badger_helper.go
storage/mysql.go
storage/store.go

close https://github.com/filecoin-project/venus/issues/5547
略微优化了一些代码的xiefa
maddr -> mAddr

fix: fix typo & opt code style

---

jwtclient/local_auth_client.go
jwtclient/local_auth_client_test.go

feat: change with secret

---

storage/mysql.go
storage/mysql_test.go

close https://github.com/filecoin-project/venus/issues/5600

fix: failed to get user by miner in mysql

---

storage/mysql.go
storage/store.go

feat: miner only binds one user

---

core/const.go

chore: bump version to 1.9.0

---

jwtclient/auth_client.go

ref https://github.com/filecoin-project/venus/issues/5384
- 在接口中 增加 UpsertMIner 方法

Feat/tanlang/adjsut jwtclient.IAuthClient / 调整 jwtclient.IAtuhClient 接口 

---

.github/workflows/docker_image.yml
Makefile

feat: github action add event on dispatch

---

CHANGELOG.md
core/const.go
go.mod
go.sum

https://github.com/filecoin-project/venus/issues/5650

chore: bump version to v1.10.0-rc1

---

auth/route.go

https://github.com/filecoin-project/venus/issues/4887

feat: add status api to detect api ready

---

CHANGELOG.md
core/const.go
go.mod
go.sum

chore: bump version to v1.10.0

---

CHANGELOG.md
core/const.go

chore: bump version to v1.10.1

---

cli/repo.go

close https://github.com/filecoin-project/venus/issues/5807

fix: repo not exist

---

auth/route.go
cli/repo.go
cli/run.go
util/util.go

https://github.com/filecoin-project/venus/issues/5807

fix: not set flag value to config

---

cli/api.go

close https://github.com/filecoin-project/venus/issues/5807

fix: cli not found config

---

auth/app.go
auth/jwt.go
auth/jwt_test.go
integrate_test/token_test.go
integrate_test/user_test.go
jwtclient/auth_client_test.go
jwtclient/utils.go

close filecoin-project/venus#5830,  close filecoin-project/venus#5820

feat: return detailed error infor after authentication failure

---

CHANGELOG.md
Makefile
core/const.go

Pre/v1.11 / 合并预发布分支

---

CHANGELOG.md
core/const.go

chore: merge release/v1.11 into master

---

Makefile
auth/app.go
auth/jwt.go
auth/jwt_test.go
auth/route.go
core/const.go
core/const_test.go
core/context.go
go.mod
go.sum
jwtclient/auth_client_test.go
jwtclient/auth_mux.go
jwtclient/auth_mux_test.go
jwtclient/inteface.go
jwtclient/local_auth_client.go
jwtclient/local_auth_client_test.go
jwtclient/utils.go

close https://github.com/filecoin-project/venus/issues/5702

opt: remove perm adapt strategy

---

auth/jwt_test.go
config/config.go
integrate_test/mock_deamon.go
jwtclient/auth_client_test.go
storage/store_test.go

chore: use io/os replace io/ioutil

---

core/const.go
core/const_test.go
core/context.go

close https://github.com/filecoin-project/venus/issues/6002

opt: Adjust the order of the permissions array

---

README.md
cli/api.go
cli/run.go
cmd/mock/main.go
cmd/server/main.go
config/config.go
config/config.toml
config/safeConfig.toml
docs/en/getting-started.md
docs/zh/快速上手.md
jwtclient/auth_client_test.go

close https://github.com/filecoin-project/venus/issues/5745

feat: add flag --listen and default listening 127.0.0.1

---

CHANGELOG.md
core/const.go

chore: bump up version to v1.12-rc1

---

CHANGELOG.md
core/const.go

chore: bump up version to v1.12.0

---

docs/zh/config-desc.md
docs/zh/快速上手.md

add more description for config / 添加更多注释给config文件

---

cli/token.go

update error info / 改善错误提示

---

core/const.go
jwtclient/auth_client.go

ref https://github.com/filecoin-project/venus/issues/5561

feat: add venus api header

---

CHANGELOG.md
core/const.go

chore: bump up version to v1.13.0

---

CHANGELOG.md
core/const.go

chore: bump version to v1.14.0-rc1

---

CHANGELOG.md
core/const.go

chore: bump version to v1.14.0

---

cli/api.go
cmd/server/main.go

close https://github.com/filecoin-project/venus/issues/6068

chore: add repo env var

---

CHANGELOG.md
core/const.go

chore: bump version to v1.15.0-rc1

---

CHANGELOG.md
core/const.go

chore: bump version to v1.15.0
